// Generated by TKG at 2016-12-31 22:32:55

#include "keymap_common.h"

#define KEYMAP_TKG( \
    K0A, K0B, K0C, K0D, K0E, K0F, K0G, K0H, K0I, K0J, K0K, K0L, K0M, K0N, K0O, \
    K1A, K1B, K1C, K1D, K1E, K1F, K1G, K1H, K1I, K1J, K1K, K1L, K1M, K1N, K1O, \
    K2A, K2B, K2C, K2D, K2E, K2F, K2G, K2H, K2I, K2J, K2K, K2L,      K2N, K2O, \
    K3A,      K3C, K3D, K3E, K3F, K3G, K3H, K3I, K3J, K3K, K3L, K3M, K3N, K3O, \
    K4A, K4B, K4C,                     K4H,      K4J, K4K, K4L, K4M, K4N, K4O, \
         K5B, K5C, K5D, K5E, K5F, K5G, K5H, K5I, K5J, K5K  \
) { \
    { KC_##K0A, KC_##K0B, KC_##K0C, KC_##K0D, KC_##K0E, KC_##K0F, KC_##K0G, KC_##K0H, KC_##K0I, KC_##K0J, KC_##K0K, KC_##K0L, KC_##K0M, KC_##K0N, KC_##K0O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K1A, KC_##K1B, KC_##K1C, KC_##K1D, KC_##K1E, KC_##K1F, KC_##K1G, KC_##K1H, KC_##K1I, KC_##K1J, KC_##K1K, KC_##K1L, KC_##K1M, KC_##K1N, KC_##K1O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K2A, KC_##K2B, KC_##K2C, KC_##K2D, KC_##K2E, KC_##K2F, KC_##K2G, KC_##K2H, KC_##K2I, KC_##K2J, KC_##K2K, KC_##K2L, KC_NO,    KC_##K2N, KC_##K2O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K3A, KC_NO,    KC_##K3C, KC_##K3D, KC_##K3E, KC_##K3F, KC_##K3G, KC_##K3H, KC_##K3I, KC_##K3J, KC_##K3K, KC_##K3L, KC_##K3M, KC_##K3N, KC_##K3O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K4A, KC_##K4B, KC_##K4C, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K4H, KC_NO,    KC_##K4J, KC_##K4K, KC_##K4L, KC_##K4M, KC_##K4N, KC_##K4O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_##K5B, KC_##K5C, KC_##K5D, KC_##K5E, KC_##K5F, KC_##K5G, KC_##K5H, KC_##K5I, KC_##K5J, KC_##K5K, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }  \
}

#ifdef KEYMAP_SECTION_ENABLE
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] PROGMEM = {
#endif
    [0] = KEYMAP_TKG(
        ESC, 1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   MINS,EQL, BSLS,HOME, \
        TAB, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   LBRC,RBRC,BSPC,PGUP, \
        LCTL,A,   S,   D,   F,   G,   H,   J,   K,   L,   SCLN,QUOT,     ENT, PGDN, \
        LSFT,     Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, SLSH,RSFT,UP,  END,  \
        FN0, LGUI,LALT,                    RCTL,     SPC, RALT,FN0, LEFT,DOWN,RGHT, \
             F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10),
    [1] = KEYMAP_TKG(
        GRV, F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, F11, F12, TRNS,INS,  \
        CAPS,FN1, FN2, FN3, FN4, FN5, FN6, TRNS,PSCR,SLCK,PAUS,TRNS,TRNS,DEL, VOLU, \
        TRNS,FN7, FN8, FN9, FN10,FN11,FN12,FN13,FN14,FN15,TRNS,TRNS,     TRNS,VOLD, \
        TRNS,     FN16,FN17,FN18,FN19,FN20,FN21,FN22,FN23,FN24,TRNS,TRNS,MPLY,PSCR, \
        TRNS,TRNS,TRNS,                    TRNS,     TRNS,TRNS,TRNS,MPRV,TRNS,MNXT, \
             TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS),
};

#ifdef KEYMAP_SECTION_ENABLE
const uint16_t fn_actions[] __attribute__ ((section (".keymap.fn_actions"))) = {
#else
const uint16_t fn_actions[] PROGMEM = {
#endif
    [0] = ACTION_LAYER_MOMENTARY(1),
    [1] = ACTION_FUNCTION(3, ),
    [2] = ACTION_FUNCTION(4, ),
    [3] = ACTION_FUNCTION(1, ),
    [4] = ACTION_FUNCTION(),
    [5] = ACTION_FUNCTION(5, 1),
    [6] = ACTION_FUNCTION(5, 2),
    [7] = ACTION_FUNCTION(5, 3),
    [8] = ACTION_FUNCTION(5, ),
    [9] = ACTION_FUNCTION(5, 4),
    [10] = ACTION_FUNCTION(5, 5),
    [11] = ACTION_FUNCTION(5, 6),
    [12] = ACTION_FUNCTION(6, ),
    [13] = ACTION_FUNCTION(5, 7),
    [14] = ACTION_FUNCTION(5, 8),
    [15] = ACTION_FUNCTION(5, 9),
    [16] = ACTION_FUNCTION(6, 1),
    [17] = ACTION_FUNCTION(5, 10),
    [18] = ACTION_FUNCTION(5, 11),
    [19] = ACTION_FUNCTION(5, 12),
    [20] = ACTION_FUNCTION(6, 2),
    [21] = ACTION_FUNCTION(5, 13),
    [22] = ACTION_FUNCTION(5, 14),
    [23] = ACTION_FUNCTION(5, 15),
    [24] = ACTION_FUNCTION(6, 3),
};